### ISSUE TITLE
Getting 'no snapshots were recorded' when upgrading the version to 2.1.0

### ISSUE THREAD

**Issue by sankar-refined** [happo/happo-playwright#8]
I am trying to upgrade the happo-playwright version from 2.0.1 to 2.1.0.

The job with the tests passes, but at the end, we get this,  "[HAPPO] No snapshots were recorded. Ignoring." 

> (Use `node --trace-warnings ...` to show where the warning was created)
  ✓  1 [happo] › test/_happo-set/e2e-set/admin/site-builder-happo.spec.ts:9:5 › site builder @r-happo @happoPlaywright (21.5s)
>   Consider splitting slow test files to speed up parallel execution
>   1 skipped
>   18 passed (6.7m)
> [HAPPO] No snapshots were recorded. Ignoring.

Not sure of what is going wrong here?

**Comment by lencioni** [comment]
Thanks for the report!

It looks like the only change that is in that version range is this single commit: https://github.com/happo/happo-playwright/commit/9f375788f3a18f6b046df7207dbdbdf7e47b8efc

Can you share some example code of how you are calling `happoPlaywright.screenshot`?

Can you also share your `.happo.js` configuration file?

**Comment by sankar-refined** [comment]
This is the example code of happoPlaywright,screenshot. We have a helper function, that calls the `happoPlaywright.screenshot`


> export async function takeHappoAdminScreenshot({
>   page,
>   locator,
>   happoPlaywright,
>   component,
>   target,
>   hideLocators,
> }: {
>   page: Page;
>   locator: Locator;
>   // eslint-disable-next-line @typescript-eslint/no-explicit-any
>   happoPlaywright: any;
>   component: string;
>   target: BrowserName;
>   hideLocators?: Array<Locator>;
> }): Promise<void> {
>   // Hide user locators
>   if (hideLocators) {
>     await hideElements(hideLocators);
>   }
> 
>   await page.waitForTimeout(HAPPO_WAIT);
>   await takeHappoScreenshot(happoPlaywright, page, locator, component, target);
> }
> 
> export async function takeHappoScreenshot(
>   happoPlaywright: any,
>   page: Page,
>   locator: Locator,
>   component: string,
>   target: BrowserName,
> ) {
>   await happoPlaywright.screenshot(page, locator, {
>     component: component,
>     variant: 'default',
>     targets: [target],
>     id: component,
>   });

happo.js

> const { RemoteBrowserTarget } = require('happo.io');
> 
> module.exports = {
>   apiKey: <apikey>
>   apiSecret: <secret>,
>   targets: {
>     chrome: new RemoteBrowserTarget('chrome', {
>       viewport: '1920x1080',
>       freezeAnimations: 'last-frame',
>       project: 'charlie',
>     }),
>   },
> };
>

**Comment by sankar-refined** [comment]
target is chromium

![image](https://github.com/user-attachments/assets/5bcea0ef-89fa-4776-abe2-bc09f1928ae2)

**Comment by lencioni** [comment]
Can you try changing the `target` to `'chrome'` or just removing that property entirely from this function call? I believe that it needs to match the target name that you have defined in your `.happo.js` config file. If you remove it I think it should use all of the targets you have configured by default, which appears to be just the one from the config file you shared.

I think that previously this was working for you because that option was not being passed through but on the new version is now being passed through as part of `...rest`.

**Comment by sankar-refined** [comment]
I changed the target to 'chrome' and happo was able to publish the snapshots
